### ISSUE TITLE
Watcher crashes when using the plugin with Astro

### ISSUE THREAD

**Issue by asiryk** [UstymUkhman/vite-plugin-glsl#29] opened 2022-12-27 13:55 UTC
I created the issue in the Astro project, but it turned out that it was the problem with the plugin itself.

https://github.com/withastro/astro/issues/5672#issuecomment-1364700977

> It's a regression by vite-plugin-glsl [here](https://github.com/UstymUkhman/vite-plugin-glsl/blob/f0b2dda188228026d31000f0d54aa2dbf9b01b50/src/watchShader.js#L60) since https://github.com/UstymUkhman/vite-plugin-glsl/commit/25fa19ef4d5424057962db2756b613b097346e2d. It relies on the Vite config file and update the utime to restart the server, it should use server.restart() instead as it's cross compatible for metaframeworks without a Vite config file. Please report upstream instead.

**Comment by UstymUkhman** [comment] 2022-12-27 14:02
Hi @asiryk , thanks for using this plugin, for the info about the issue and for a hint on how to solve it.
One question: can I use [this](https://github.com/asiryk/subject_ms-VGGI) repo as a "Minimal Reproducible Example" in order to test & fix the utime to restart the server? I would really appreciate it, thanks!

**Comment by asiryk** [comment] 2022-12-27 14:03
> can I use [this](https://github.com/asiryk/subject_ms-VGGI) repo as a "Minimal Reproducible Example"

Yes, sure!

**Comment by UstymUkhman** [comment] 2022-12-28 11:42
Hi again @asiryk. I might need your help here. I've updated this plugin to `v1.0.2` in order to use `server.restart()` when watching shader files, and tried that version on your repo after running and `npm update`. The good news is that it doesn't crash in the console anymore, it's actually trying to reload the server with newer `.glsl` file, but when doing so, the server gets disconnected in the browser with an error from *vite* or *astro* config file.

Unfortunately, I'm not quite familiar with the second one, so I thought you might be able to give me some hint since I've checked this plugin update with vite *v4* and *v3* and it's working just as expected. At this point I assume it's an issue with astro or your configuration of the repo I've tested on. I'll leave this issue open until you'll be able to use hot reloading as intended, so please let me know if you'll need any help from my side. Thanks for your ⭐ and good luck!

**Comment by asiryk** [comment] 2022-12-28 11:46
Hi, thanks, I'm not very familiar with Astro either, I use almost default configs. But I'll check.

**Comment by UstymUkhman** [comment] 2023-01-06 16:32
Hi @asiryk , I think I've found a workaround to this issue. I've tested it in your repo and it seems to be working, so please try it by adding the following server config in `astro.config.mjs`:

```
import { defineConfig } from 'astro/config';
import glsl from 'vite-plugin-glsl';

// https://astro.build/config
export default defineConfig({
  vite: {
    plugins: [glsl()],

    server: {
      port: 3000
    }
  }
});
```

I've submitted an issue to the astro team in [here](https://github.com/withastro/astro/issues/5783) 'cause it seems to me like this problem is on their side since the latest `vite-plugin-glsl` version is working properly with vite 3 & 4.

Let me know if that works for you and if I can help in some other way. Good luck!

**Comment by asiryk** [comment] 2023-01-06 17:23
Hi @UstymUkhman, sorry it took me so long to respond. This is a project for my school, I wanted to take a small break from it 😅

Yes, seems like the issue is with astro. Your config in `astro.config.mjs` works just fine. Interestingly the same doesn't apply for `astro.config.ts` although [it says](https://docs.astro.build/en/guides/configuring-astro/#supported-config-file-types) that `.ts` config is supported.

Thank you so much for helping and stay safe <3

**Comment by UstymUkhman** [comment] 2023-01-08 08:29
One last quick update: it seems to be working well even if we don't specify vite's server config, but disable plugin's `watch` option. Like mentioned [here](https://github.com/withastro/astro/issues/5783#issuecomment-1374490731), astro will handle HMR and fetch the latest shader version by itself, at least that worked when I tested it [here](https://stackblitz.com/edit/github-ctfwyn?file=astro.config.mjs) with `v1.9.1`. So it thet works for you too, feel free to use the preferred workaround between the two.

I'm closing this issue now since it's not directly related to this plugin anymore and there are a coupe hacks that should work when `vite-plugin-glsl` is used with astro. Thanks again and good luck!

**Closed by UstymUkhman** 2023-01-08 08:29 UTC
Labels: bug, enhancement, needs help
