### ISSUE TITLE
Typscript Support for Importing Shaders

### ISSUE THREAD

**Issue by ryandurkoske** [UstymUkhman/vite-plugin-glsl#30] opened 2023-01-08 20:02 UTC
Missing module declarations for the shader file extensions. 

Easy solution and its the only thing missing for complete typscript support.

Add:

glsl.d.ts
vert.d.ts
frag.d.ts

ex. 

`
declare module '*.glsl' {
	const content: string;
	export default content;
}
`

**Comment by UstymUkhman** [comment] 2023-01-09 09:03
@ryandurkoske Good one, thanks! Just to double check: you mean something like [this](https://github.com/UstymUkhman/vite-plugin-glsl/blob/b14376301d84da18e2c08a3c64b0fa38e862d7b7/src/ext.d.ts), right? So, if necessary, this will also allow you to import these module declarations like this:

```
/// <reference types="vite-plugin-glsl/ext" />
```

Have I missed something here?

**Comment by UstymUkhman** [comment] 2023-01-15 15:15
I guess that's it. Closing this one since `v1.1` was just released with this update, thanks!

**Comment by ryandurkoske** [comment] 2023-01-18 01:41
Yep that’s perfect! Sorry don’t check GitHub much, but that’s definitely better than my crude solution, haha.

**Comment by Cosmic-Goat** [comment] 2023-01-18 05:45
> @ryandurkoske Good one, thanks! Just to double check: you mean something like [this](https://github.com/UstymUkhman/vite-plugin-glsl/blob/b14376301d84da18e2c08a3c64b0fa38e862d7b7/src/ext.d.ts), right? So, if necessary, this will also allow you to import these module declarations like this:
> 
> ```
> /// <reference types="vite-plugin-glsl/ext" />
> ```
> 
> Have I missed something here?

I had to change the reference path to include the `src` directory in order for TypeScript to find the `ext.d.ts` file:   
```typescript
/// <reference types="vite-plugin-glsl/src/ext" />
```
Once I did that, it worked just fine. (and thank you for the great project!)

**Comment by UstymUkhman** [comment] 2023-01-18 09:20
@Cosmic-Goat Hmm.., actually I was expecting it to work like this: `/// <reference types="vite-plugin-glsl/ext" />`.
As described by the [docs](https://nodejs.org/api/packages.html#subpath-exports), it should be possible if your node version is `>= 12.7.0`. If you're sure about that, then I've probably messed up something in [here](https://github.com/UstymUkhman/vite-plugin-glsl/blob/main/package.json#L32), I will double check that, thanks!

**Comment by Cosmic-Goat** [comment] 2023-01-18 17:25
@UstymUkhman I'm using node `19.4.0`. In my original project I'm using Astro and pnpm (which I thought might be the cause), but I just tried using just an empty Vite project with Yarn v1 and still got the same issue, so I can confirm it's probably something with the package.

**Comment by UstymUkhman** [comment] 2023-01-18 18:09
@Cosmic-Goat Yep, totally. I've tested too today with yarn & plain vite and it wasn't working without specifying the `src` directory, so I'm gonna try to fix this. Thanks for checking and for your star, I really appreciate that! ❤️

**Comment by UstymUkhman** [comment] 2023-01-20 08:30
Closing this since version `1.1.1` was just released with a fix for that. Thanks!

**Closed by UstymUkhman** 2023-01-20 08:30 UTC
Labels: enhancement
